### ISSUE TITLE
Master Issue: Current release of eXist crypto lib 5.3.0 has known fatal issues

### ISSUE THREAD

**Issue by joewiz** [eXist-db/crypto-exist-java-lib#33]
The current release of the eXist crypto library package, 5.3.0, has the following flaws:

1. It contains code intended to work only in eXist 5.3.0-SNAPSHOT+, but its minimum version dependency is eXist 4.4.0, so users of eXist 4.4.0+ will get a package intended for eXist 5.3.0-SNAPSHOT. (See screenshot.)
2. It has the wrong abbrev. This is on top of a history of changed package names/URIs and abbrevs. This can lead to users installing multiple parallel versions of the app, and the public-repo offering multiple versions. (See screenshot.)
3. It has a duplicate function signature, so importing it into an XQuery module will raise errors. It is broken.
4. The code this release was built from is not in this repository's source control.

See 
> <img width="1296" alt="Screen Shot 2020-11-30 at 2 27 31 PM" src="https://user-images.githubusercontent.com/59118/100655481-564cba00-3319-11eb-88c4-d2ba6ba50afd.png">

Action items:

- [x] Post notice about this issue to README, exist-open, and Slack.
- [x] Locate code that this release was built from.
- [x] Release a new version targeting eXist 4.x through 5.2, ensuring these spans of eXist don't fetch the bad version. May need to add a log message in post-install warning users of possible parallel installation.
- [x] Release a new major version offering eXist 5.3.0 compatibility.

**Comment by line-o** [comment]
I think we can close this now @joewiz

**Comment by windauer** [comment]
with the 6.0.0 release today I agree that this ticket can be close @joewiz , @line-o

**Comment by line-o** [comment]
closed by #37
